# Markdownlint configuration.

# For more information, see: https://github.com/DavidAnson/markdownlint#optionsconfig.

# Enable all rules.
default: true

# Line Length.
#
# NOTE: The line_length rule is currently not strict enough.
# For more details, see: https://github.com/DavidAnson/markdownlint/issues/237.
MD013:
  # Allow longer lines for code blocks since account ids are 64 characters long
  # by themselves.
  code_block_line_length: 99

# Inline HTML.
MD033:
  allowed_elements:
    # Allow raw <code> ... </code> elements because we use it as a work-around
    # for lack of Vuepress' support for inline double curly braces that we use
    # for denoting variables.
    # For more details, see: https://github.com/vuejs/vuepress/issues/853.
    - code

MD024:
  # This allows us to have duplicate headings as long as they're not siblings
  siblings_only: true
