version: 2.1


jobs:
  preflight:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Ensure docs built
          command: |
            mtime=$(git ls-files | grep -v docs/ | xargs ls -t | head -n1 | xargs stat -c %Y)
            docstime=$(stat -c %Y docs)
            if (($mtime > $docstime)); then
              echo "Please run \`vuepress build\` and push a new commit."
              exit 1
            fi


workflows:
  version: 2

  test:
    jobs:
      - preflight
