name: Continuous integration

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run markdownlint
        # TODO: Expand this to other files in this repo.
        run: npx markdownlint-cli src/operators/
