name: vuepress
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npx prettier --write --trailing-comma=all --single-quote src/.vuepress/config.js
    - name: build docs
      run: |
        git config --global user.name "nhynes"
        git config --global user.email "nhynes@oasislabs.com"
        cd src
        vuepress build
        cd .vuepress/dist
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oasislabs/docs.git
        git checkout -b gh-pages
        git add .
        git commit -m "Update docs"
        git fetch origin gh-pages
        git rebase origin/gh-pages -X ours
        git push -u origin gh-pages
