name: vuepress

on: page_build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npx vuepress build
    - name: commit docs
      run: |
        git config --global user.name "ryscheng-bot"
        git config --global user.email "ryscheng-bot@oasislabs.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/oasislabs/docs.git
        git commit -am "Update docs/"
        git push origin HEAD:master
