name: vuepress

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: vuepress build
      run: |
        npm install -g vuepress
        vuepress build
    - name: commit docs
      run: |
        git config --global user.name "ryscheng-bot"
        git config --global user.email "ryscheng-bot@oasislabs.com"
        git add docs/
        git commit -m "Build docs"
        git remote set-url origin https://$GITHUB_TOKEN@github.com/oasislabs/docs.git
        git push origin HEAD:$GITHUB_REF
